### ISSUE TITLE
RuntimeError: Event device  does not match recording stream's device

### ISSUE THREAD

**Issue by framolfese** [microsoft/RetrievalAttention#15]
Hi,

I'm running RetroInfer on a machine with 8 A100 GPUs with 40GBs each. When running [Qwen2.5-7B-Instruct-1M](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-1M) on [LongBench-v2](zai-org/LongBench-v2), I encounter the following error:

```bash
Traceback (most recent call last):
  File "/home/ec2-user/workplace/RetrievalAttention/benchmark/LongBench-v2/pred.py", line 205, in <module>
    get_pred(
  File "/home/ec2-user/workplace/RetrievalAttention/benchmark/LongBench-v2/pred.py", line 114, in get_pred
    out = llm.generate(
  File "/home/ec2-user/workplace/RetrievalAttention/model_hub/LLM.py", line 226, in generate
    outputs = self.inference(inputs_ids)
  File "/home/ec2-user/workplace/RetrievalAttention/model_hub/LLM.py", line 185, in inference
    logits = self.decode_forward(inputs_ids=output_ids)
  File "/home/ec2-user/workplace/RetrievalAttention/model_hub/LLM.py", line 151, in decode_forward
    hidden_states = self.layer_decode(ldx, hidden_states)
  File "/home/ec2-user/workplace/RetrievalAttention/model_hub/LLM.py", line 106, in layer_decode
    key_states, value_states = self.kv_cache.decode_update_kv_cache(key_states, value_states, layer_idx)
  File "/home/ec2-user/workplace/RetrievalAttention/cache_hub/retroinfer_cache.py", line 513, in decode_update_kv_cache
    self._update_kv_cache()
  File "/home/ec2-user/workplace/RetrievalAttention/cache_hub/retroinfer_cache.py", line 446, in _update_kv_cache
    self.mainevents[self.layer_mapping[str(ldx)]].record()
  File "/home/ec2-user/miniconda3/envs/retroinfer/lib/python3.10/site-packages/torch/cuda/streams.py", line 185, in record
    super().record(stream)
RuntimeError: Event device  does not match recording stream's device 
```

The error happens with any combination of GPUs. The only one that seems to work is when I use a single GPU, but then it crashes for OOM reasons. Could you help me solve this issue?

**Comment by framolfese** [comment]
I just want to specify that running that model on InfiniteBench works just fine with any 2 or more GPUs.

**Comment by Komorebi660** [comment]
Hi, thank you for your feedback. We have fixed this bug and updated the repository. You can try it again now.

**Comment by framolfese** [comment]
Thanks for you help, the issue seems to be resolved. I'm closing the issue.
